version: '3.8'

services:

  backend-cud:
    container_name: backend-cud
    image: junwon1131/s208-backend-cud:latest
    build:
      context: ./backend-cud
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
#    depends_on:
#      - redis

  backend-cud-service:
    container_name: your-new-service
    image: junwon1131/s208-backend-cud-kubernetes:latest
    build:
      context: ./backend-cud
      dockerfile: Dockerfile.kubernetes
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - jenkins-network

networks:
  jenkins-network:
    external: true


volumes:
  jenkins_home:
  prometheus_data:
  grafana_data:
  secrets:
