apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-cud
  template:
    metadata:
      labels:
        app: backend-cud
    spec:
      containers:
        - name: backend-cud
          image: my-docker-registry/my-webapp-image:latest
          ports:
            - containerPort: 8080
