apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-cud-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
spec:
  rules:
    - host: hello-minikube.local
      http:
        paths:
          - path: /cud(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-cud-service
                port:
                  number: 8080
