apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-controller-admin
subjects:
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: ingress-nginx
