apiVersion: v1
kind: Service
metadata:
  name: backend-cud-service
spec:
  selector:
    app: backend-cud
  ports:
    - protocol: TCP
      port: 8080  # 여기를 80에서 8080으로 변경
      targetPort: 8080
  type: LoadBalancer
