spring:

  profiles:
    include: oauth

  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: localhost
      port: 6379
      password: 'test1234'

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 56933131412-secpaj90db6jjv86v66mkvstlhsvtdol.apps.googleusercontent.com
            client-secret: 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
            #            redirect-uri: https://j10c102.p.ssafy.io/login/oauth2/code/google
            #            redirect-uri: http://localhost:8080/login/oauth2/code/google
            #            http://localhost:8080/microsoft-signin
            scope: profile, email

          azure:
            client-id: 02331f7f-ee11-47ae-97ba-44f60702dabd
            client-secret: Af68Q~uuJuRvS7JgX4dkCoZF30jbdTeJ5r.9YaTC
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/microsoft
            scope: User.Read, Mail.Read
            client-name: Microsoft

        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/1dd045fe-2d3b-4520-8730-69b5874d374e/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/1dd045fe-2d3b-4520-8730-69b5874d374e/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: name


  jwt:
    access: whatwehavetowantinalifeismentalsatisfactionnotmaterialone
    refresh: youforgetthisyoualwaysfeelfailevenifyouwillgeteverything
    accesstime: 360000000  # 10H -> 0?? ? ??...
    refreshtime: 604800000 # 7Days


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # SSE ??? ?? -> DB Connection ??? connection ?? ??

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

cloud:
  aws:
    credentials:
      access-key: AKIAW3MEAWFWGVMIB3VX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: fullerting-s3-v2
      stack:
        auto: false

logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG

server:
  port: 8080
  servlet:
    context-path: /


