spring:

  profiles:
    include: oauth

  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: localhost
      port: 6379
      password: 'test1234'

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 56933131412-secpaj90db6jjv86v66mkvstlhsvtdol.apps.googleusercontent.com
            client-secret: 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
            #            redirect-uri: https://j10c102.p.ssafy.io/login/oauth2/code/google
            #            redirect-uri: http://localhost:8080/login/oauth2/code/google
            #            http://localhost:8080/microsoft-signin
            scope: profile, email

          microsoft:
            client-id: 02331f7f-ee11-47ae-97ba-44f60702dabd
            client-secret: fdeb56a9-1f3c-4ce4-8bae-6ff2159f1c3f
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/microsoft
            scope: User.Read, Mail.Read
            client-name: Microsoft

        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: name


  jwt:
    access: whatwehavetowantinalifeismentalsatisfactionnotmaterialone
    refresh: youforgetthisyoualwaysfeelfailevenifyouwillgeteverything
    accesstime: 360000000  # 10H -> 0?? ? ??...
    refreshtime: 604800000 # 7Days


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # SSE ??? ?? -> DB Connection ??? connection ?? ??

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html


logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG

server:
  port: 8080
  servlet:
    context-path: /
  websocket:
    port: 9090

