spring:

  profiles:
    include: oauth

  datasource:
    url: jdbc:mysql://localhost:3306/backend?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: localhost
      port: 6379
#      password: 'test1234'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # SSE ??? ?? -> DB Connection ??? connection ?? ??

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG

server:
  port: 8080
  servlet:
    context-path: /


