spring:

  profiles:
    include : oauth

  datasource:
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jackson:
    time-zone: Asia/Seoul

  data:
    redis:
      host: localhost
      port: 6379
      password: 'test1234'

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 56933131412-secpaj90db6jjv86v66mkvstlhsvtdol.apps.googleusercontent.com
            client-secret: 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
            #            redirect-uri: https://j10c102.p.ssafy.io/login/oauth2/code/google
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: profile, email



  jwt:
    access: whatwehavetowantinalifeismentalsatisfactionnotmaterialone
    refresh: youforgetthisyoualwaysfeelfailevenifyouwillgeteverything
    accesstime: 360000000  # 10H -> 0?? ? ??...
    refreshtime: 604800000 # 7Days

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB


  jpa:
    show-sql: false  # jpa ??? ?? ??
    hibernate:
      ddl-auto: update  # Hibernate? ???? ???? ????? ??
    properties:
      hibernate:
        format_sql: true
    open-in-view: false  # SSE ??? ?? -> DB Connection ??? connection ?? ??

cloud:
  aws:
    credentials:
      access-key: AKIAW3MEAWFWGVMIB3VX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: fullerting-s3-v2
      stack:
        auto: false

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html


logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG


fcm:
  service-account-file: key/fullerting-fcm-firebase-adminsdk-rjmjj-0e19a90e90.json
  topic-name: alarm
  project-id: fullerting-fcm

#      hibernate:
#        type:
#          descriptor:
#            sql: trace


server:
  port: 8080
  servlet:
    context-path: /
  websocket:
    port: 9090

#  tomcat:
#    remoteip:
#      protocol-header: x-forwarded-proto

